general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = ~/.config/hypr/lid-dpms.sh
}

# Lock na 5 minuten
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Scherm uit na 1 uur
listener {
    timeout = 3600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend na 2 uur
listener {
    timeout = 7200
    on-timeout = systemctl suspend
}
